name: Scan-powershell

on:
  workflow_dispatch:
    inputs:
      do-translation:
        description: 'Run Fortify translation step'
        type: boolean
        default: false

  #push:
    #branches: [ main ]

jobs:
  Scan_Fortify:
    runs-on:
      group: Fortify
    env:
      FORTIFY_SSC_URL: ${{ vars.FORTIFY_SSC_URL }}
      FORTIFY_SC_URL: ${{ secrets.FORTIFY_SC_URL }}
      FORTIFY_BUILD: ${{ vars.FORTIFY_BUILD }}
      FORTIFY_VERID: ${{ vars.FORTIFY_VERID }}
    
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Mark workspace as safe for Git
        shell: powershell
        run: |
          git config --global --add safe.directory "${{ github.workspace }}"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Fortify Translation
        if: ${{ github.event.inputs.do-translation == 'true' }}
        run: |
          sourceanalyzer -b $env:FORTIFY_BUILD -clean
          sourceanalyzer -b $env:FORTIFY_BUILD .\Eightball.java -source 11
        shell: powershell

      - name: Run Fortify Scan
        if: ${{ github.event.inputs.do-translation == 'true' }}
        run: |
          $output = scancentral -url $env:FORTIFY_SC_URL start -upload `
            -versionid $env:FORTIFY_VERID `
            -uptoken $env:FORTIFY_SC_CRTL_TOKEN `
            -b $env:FORTIFY_BUILD `
            -scan | Out-String

          Write-Host "Fortify Scan Output: $output"

          # Usar -match para extraer el token
          if ($output -match "Submitted job and received token:\s*(\S+)") {
              $token = $matches[1]
          } else {
              $token = "No token found"
          }

          Write-Host "Token extraido: $token"
          echo "FORTIFY_JOB_TOKEN=$token" >> $env:GITHUB_ENV
        env:
          FORTIFY_SC_CRTL_TOKEN: ${{ secrets.FORTIFY_SC_CRTL_TOKEN }}
        shell: powershell
      
      - name: LogIn Fortify SSC and SC-SAST
        run: |
          Write-Host "Logging in to Fortify SSC and SC-SAST"
          fcli config truststore set -f="C:\Program Files\Java\jdk-23\lib\security\cacerts"
          fcli ssc session login --url $env:FORTIFY_SSC_URL --user $env:FORTIFY_SSC_USER --password $env:FORTIFY_SSC_PASS
          
          fcli sc-sast session login --ssc-url $env:FORTIFY_SSC_URL -t $env:FORTIFY_CI_TOKEN -c $env:FORTIFY_CLIENT_AUTH_TOKEN --connect-timeout 30s
        env:
          FORTIFY_SSC_USER: ${{ secrets.FORTIFY_SSC_USER }}
          FORTIFY_SSC_PASS: ${{ secrets.FORTIFY_SSC_PASS }}
          FORTIFY_CI_TOKEN: ${{ secrets.FORTIFY_CI_TOKEN }}
          FORTIFY_CLIENT_AUTH_TOKEN: ${{ secrets.FORTIFY_CLIENT_AUTH_TOKEN }}  
        shell: powershell

      - name: Approve Artifact
        if: ${{ github.event.inputs.do-translation == 'true' }}
        run: | 
          Write-Host "Approving Artifact token: ${{env.FORTIFY_JOB_TOKEN}}"  

          fcli sc-sast scan wait-for $env:FORTIFY_JOB_TOKEN

          $artifactId = (fcli ssc artifact list --av=$env:FORTIFY_VERID --output=json | ConvertFrom-Json)[0].id
          
          echo "ARTIFACT_ID=$artifactId" >> $env:GITHUB_ENV
          
          fcli ssc artifact approve $artifactId
        shell: powershell

      - name: Download Fortify Report
        run: |
          Write-Host "Downloading Fortify Report for Artifact ID: ${{env.ARTIFACT_ID}}"
          fcli ssc artifact download ${{env.ARTIFACT_ID}} -f $env:FORTIFY_BUILD.fpr
          
      - name: Upload FPR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fortify-fpr
          path: ${{vars.FORTIFY_BUILD}}.fpr
      - name: Run Github-SAST-Report
        run: |
          fcli ssc action run github-sast-report --appversion $env:FORTIFY_VERID --file $env:FORTIFY_BUILD.fpr.sarif

      - name: Upload Sarif Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fortify-fpr-sarif
          path: ${{vars.FORTIFY_BUILD}}.fpr.sarif

      - name: Upload SARIF File
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{vars.FORTIFY_BUILD}}.fpr.sarif
          category: Fortify
          
